### ISSUE TITLE
Try to eliminate `binutils` on Linux

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/openblas-feedstock#1]
This can't be done at present because a newer version was required to Linux to build at all (see this [comment]( https://github.com/conda-forge/staged-recipes/pull/364#issuecomment-210244488 ) and the one [below]( https://github.com/conda-forge/staged-recipes/pull/364#issuecomment-210279462 )). According to this [user]( https://groups.google.com/forum/#!msg/julia-users/m8chhG35bvw/YdudAoARCQAJ ), they were able to build with binutils 2.25.1. We have the binutils 2.26 package at present. As we are going to start [using devtools-2]( https://github.com/pelson/Obvious-CI/pull/61 ), we will have a binutils version in-between the two mentioned (2.23.52). It is unclear if that is new enough to work here, but it would be worth trying. If it does work, we should drop the `binutils` dependency.

**Comment by tkelman** [comment]
devtoolset-2 should be new enough. It does strange things with the way it links against libgfortran and libstdc++ though, which may cause issues. It's easier than rebuilding a latest gcc from source which is the other alternative for that problem.

**Comment by jakirkham** [comment]
Yeah, that is the plan for the near term. Though this issue has gotten a fair bit of discussion. It may be that devtoolset-2 is not enough because there are a couple C++14 use cases. To get a bit more history (and also feel free to weigh into the discussion), take a look at this issue ( https://github.com/conda-forge/conda-forge.github.io/issues/29 ). Sorry, it's a long read.

**Comment by tkelman** [comment]
I'm working on a gcc-6-on-centos-6 docker image at the moment, which I'll put up once I can get it into a shape where it can build all of Julia successfully (which depends on openblas).

**Comment by jakirkham** [comment]
As this started to get kind of long and felt more related with aforementioned issue, I have moved added [my response]( https://github.com/conda-forge/conda-forge.github.io/issues/29#issuecomment-215703119 ) there.

**Comment by jakirkham** [comment]
Attempting to remove the `binutils` package in this PR ( https://github.com/conda-forge/openblas-feedstock/pull/3 ).

**Comment by jakirkham** [comment]
Worked great. So, we have dropped the `binutils` package for future builds.
