### ISSUE TITLE
add alt arches for ilp64

### ISSUE THREAD

**Issue by ngam** [conda-forge/openblas-feedstock#131]
https://github.com/xianyi/OpenBLAS#supported-cpus-and-operating-systems

- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ngam** [comment]
This is way too complicated for me to attempt on my own, so please help: @isuruf @h-vetinari. We would like alt arches (arm64, aarch64) support for julia for ilp64 variants. Thanks!

**Comment by ngam** [comment]
My starting point would be to take the conditions out in https://github.com/conda-forge/openblas-feedstock/blob/master/recipe/conda_build_config.yaml and hope for the best lol

**Comment by h-vetinari** [comment]
I was wondering why Julia needs [`ILP64`](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models). Found the [following](https://julialang.org/blog/2021/11/julia-1.7-highlights/#libblastrampoline_mkljl) (excerpt):

> Note that Julia's choice to use ILP64 or LP64 _is_ still a compile-time decision, and that even if you load `OpenBLAS32_jll` to provide LP64 symbols, Julia will still use ILP64 on 64-bit platforms by default. The main reason to support LP64 on 64-bit platforms at all is to provide the symbols for other programs that may be linked into Julia's namespace, such as using `PyCall` to load `numpy`.

I don't pretend to understand the problem space very well, but I don't see immediately why julia in conda-forge needs ILP64? At least, I believe we control enough that "other programs that may be linked into Julia's namespace" have all the symbols they'd need.

You can also see how little ilp64 is used in conda-forge with the download numbers of this feedstock (last x86 builds):
| | linux-x86 | osx-x86 | osx-arm64 |
|--|-|-|-|
| `libopenblas-0.3.18*` | 1'138'070 | 175'901 | 17'968 |
| `libopenblas-ilp64-0.3.18*` | 3'536 | 423 | <how big do we expect this to be?> |

**Comment by ngam** [comment]
> <how big do we expect this to be?>

probably scales with the one above, 40ish.

**Comment by ngam** [comment]
@h-vetinari don't overthink it. I certainly did not. Currently, we depend on openblas-ilp64 in julia (btw, are you interested in working on julia with us? We are making a lot of progress), and we want to support more arches (this is going to be a pretty long process, so no rush).

> I don't see immediately why julia in conda-forge needs ILP64

See this comment: https://github.com/conda-forge/julia-feedstock/pull/181#issuecomment-1008332336

**Comment by h-vetinari** [comment]
> See this comment: [conda-forge/julia-feedstock#181 (comment)](https://github.com/conda-forge/julia-feedstock/pull/181#issuecomment-1008332336)

Ah, I wasn't aware of that. Happy to defer to Isuru on this.

**Comment by ngam** [comment]
> Found the [following](https://julialang.org/blog/2021/11/julia-1.7-highlights/#libblastrampoline_mkljl) (excerpt)

Btw... thank you for this. I ended up watching this Youtube video (https://www.youtube.com/watch?v=t6hptekOR7s) and now I understand this a little bit better. 

Also, the issue with cross-compile seems easy enough (for osx-arm64 it is failing because objconv needs to be called --- if not in host reqs, it would be missing; if in host reqs, it would be wrong CPU type; I have no idea how to reconcile this), and I am sure @isuruf (or you!) would be able to fix it in no time :)

**Comment by mkitti** [comment]
@ngam where did we leave this?
