### ISSUE TITLE
Problems on osx-arm (correctness & speed)

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/openblas-feedstock#143]
Known issues currently with 0.3.20 & 0.3.21 (before, certain kernels weren't activated for osx-arm yet):
* https://github.com/numpy/numpy/issues/21950
* ~https://github.com/numpy/numpy/issues/22025~ - this is a known issue for all versions of openblas including 0.3.18
* https://github.com/xianyi/OpenBLAS/issues/3735
* https://github.com/scipy/scipy/issues/16767 - also an issue with 0.3.18
* ~https://github.com/ContinuumIO/anaconda-issues/issues/12855~ - not a conda-forge issue

There's also a performance drop by factor 3-4 compared to compiling locally mentioned in the openblas issue. Not sure if this has anything to do with https://github.com/conda-forge/openblas-feedstock/commit/7dac2534b3d9ddc789c06f3f9ba16af628383a09, or why we added that at the time.

Related: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/304

CC @conda-forge/openblas @rgommers

**Comment by isuruf** [comment]
Most of the issues above are not related to 0.3.20 or above. They are present in 0.3.20 as well. Only two issues above are regressions in 0.3.20. We can fix those by setting the TARGET.
Also, the speed issue is very vague without any reproducer, so please don't involve that in any discussion until there's a reproducer.

**Comment by h-vetinari** [comment]
@isuruf 

Even with the latest libgfortran builds, it seems that there are still some open issues.

```
import numpy as np

np.linalg.det(np.array([[1, 0, 0, 0],
                        [0, 1, 3.8307904270117927e-146, 0],
                        [0, 3.8307904270117927e-146, 1.4674955295685193e-291, 0],
                        [0, 0, 0, 0]]))
```

The above should return 0, but apparently returns NaN, see https://github.com/numpy/numpy/issues/22025.

**Comment by h-vetinari** [comment]
Ah, just saw that the OP has been edited (sorry, harder to see everything on a phone), and that this is considered a known issue. Is there an upstream issue to refer to?

**Comment by isuruf** [comment]
I meant it's an issue for older versions as well which means it's not a packaging problem.
