### ISSUE TITLE
Rebuild 0.3.21 with -fno-tree-vectorize for gfortran

### ISSUE THREAD

**Issue by mattip** [conda-forge/openblas-feedstock#149]
Over at scipy/scipy#16949 it seems the new default for `-O2` is to turn on `-ftree-vectorize` which caused problems for current OpenBLAS releases. Pending a 0.3.22 release, this feedstock should be [built with `-fno-tree-vectorize`](https://github.com/scipy/scipy/issues/16949#issuecomment-1423050873)

**Comment by mattip** [comment]
Rebuilding would make #148 obsolete.

**Comment by h-vetinari** [comment]
> Pending a 0.3.22 release, this feedstock should be [built with `-fno-tree-vectorize`](https://github.com/scipy/scipy/issues/16949#issuecomment-1423050873)

Now that 0.3.22 was released, can we close this issue?

**Comment by mattip** [comment]
Yes, closing.
