### ISSUE TITLE
Add pkg-config files

### ISSUE THREAD

**Issue by isuruf** [conda-forge/openblas-feedstock#21]
`blas.pc`, `cblas.pc` and `lapack.pc` can be added so that software using pkg-config can detect the blas package to be used.

**Comment by jschueller** [comment]
that's an upstream issue https://github.com/xianyi/OpenBLAS/issues/598

**Comment by jakirkham** [comment]
It is a great idea. Though I agree with @jschueller that upstream should take this one.

**Comment by isuruf** [comment]
Upstream PR, https://github.com/xianyi/OpenBLAS/pull/1084

**Comment by isuruf** [comment]
Upstream PR got merged.

**Comment by jakirkham** [comment]
Well, do you want to patch our copy of OpenBLAS then? FWIW I'd be ok with that unless there is a good reason not to.
