### ISSUE TITLE
Backport PR #1299 from upstream

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/openblas-feedstock#42]
It would be good to backport a patch from PR ( https://github.com/xianyi/OpenBLAS/pull/1299 ). Sounds like this has caused a lot of people grief with `numpy` as noted in issue ( https://github.com/conda-forge/numpy-feedstock/issues/60 ). The patch is pretty small. Also seems free of API changes. So hopefully this goes cleanly without too much trouble.

**Comment by jschueller** [comment]
Closed several releases ago.
