### ISSUE TITLE
package is missing dependency on make and is using toolchain AR, RANLIB

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/openblas-feedstock#58]
needs these three patches
https://github.com/Archiconda/openblas-feedstock/commit/8f4dd92522d8134b479d1581da7d3530dde67bc4

https://github.com/Archiconda/openblas-feedstock/commit/5194c67d3c0961110caf34376a2f80caaaa47c65

https://github.com/Archiconda/openblas-feedstock/commit/c6bc1f0b36d7c20cc046e609f6c7bed9ec8cef4c
but it seems there is a synch with anaconda repos going on, so it will have to wait I guess???

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/openblas-feedstock/pull/89
