### ISSUE TITLE
python 2.7 and openblas incompatible on windows

### ISSUE THREAD

**Issue by moorepants** [conda-forge/openblas-feedstock#65]
Issue:

I'm getting this error:

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - openblas=0.3.3
  - python=2.7
Use "conda search <package> --info" to see the dependencies for each package.
```
on a feedstock build here:

https://github.com/conda-forge/slycot-feedstock/pull/18

Also if if try `conda create -n test python=2.7 openblas` on a windows computer it fails to resolve the dependencies with an incompatibility.

Is openblas + py27 supported?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by isuruf** [comment]
> Is openblas + py27 supported?

No. See https://conda-forge.org/docs/maintainer/knowledge_base.html#blas on how to link against blas.
