### ISSUE TITLE
Request: Please create version with `make USE_OPENMP=1` 

### ISSUE THREAD

**Issue by jolespin** [conda-forge/openblas-feedstock#79]
Is there a way to fix this via conda installation?  I can't seem to get this to work. 

Essnentially, I'm asking if there is a precompiled version I can install via conda that has USE_OPENMP=1? 

I've posted a question on StackOverflow but I haven't gotten any bites:
https://stackoverflow.com/questions/57257712/how-to-fix-openblas-warning-detect-openmp-loop-and-this-application-may-hang

If I do a separate install via [this post](https://stackoverflow.com/questions/34578526/how-to-make-openblas-work-with-openmp) I fear that my conda environment will break.

These GitHub issues might help:
https://github.com/BinPro/CONCOCT/issues/232
https://github.com/bxlab/metaWRAP/issues/168

**Comment by isuruf** [comment]
Done. `conda install libopenblas=*=*openmp*`

**Comment by LucasMS** [comment]
For those who landed here and can not find the package during installation, try:

```
conda install libopenblas=*=*openmp* --channel conda-forge
```

**Comment by Zepeng-Mu** [comment]
Hi, I got this error: `zsh: no matches found: libopenblas=*=*openmp*`.
Am I supposed to replace teh `*` with something else?

Thanks!

**Comment by jakirkham** [comment]
@Zepeng-Mu would place single quotes (`'`) around it. The shell is trying to interpret the `*` before they are passed to `conda`, which we don't want it to do. Placing it in single quotes will keep the shell from touching it.
