### ISSUE TITLE
set openblas-0.3.3 to broken

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/openblas-feedstock#85]
In `conda-meta/pinned` I have: 
```
libblas[build=*mkl]
```

Still when I try to install mumps which enforces openblas it tries to install: 
```
  mumps              conda-forge/linux-64::mumps-5.1.2-blas_openblash15930f7_1001
  openblas           conda-forge/linux-64::openblas-0.3.3-h9ac9557_1001
```

So it seems to be that `openblas` version `0.3.3` can be installed next to `mkl`, which causes issues during updating. Can you set `openblas` version `0.3.3` to broken?

**Comment by isuruf** [comment]
`openblas` can be installed next to `mkl` and should be. Please raise this issue in `mumps`.
